version: 0.2 
phases: 
  install: 
    runtime-versions: 
      golang: 1.13
      docker: 18
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email)
  build: 
    commands: 
      - CGO_ENABLED=0 go build
      - docker build -t bmo .
      - docker tag bmo:latest $REPOSITORY_URI:latest
  post_build:
    commands:
      - docker push $REPOSITORY_URI:latest
      - printf '[{"name":"bmo","imageUri":"%s"}]' $REPOSITORY_URI:latest > imagedefinitions.json
artifacts: 
  files: 
    - imagedefinitions.json